### ISSUE TITLE
MVPリリースについての質問

### ISSUE THREAD

**Issue by koseki0830** [koseki0830/imaginary_movie#104]
お疲れ様でございます。
ユーザーが架空の映画を投稿し、他のユーザーが架空でレビューを投稿するというアプリを制作しています。
実装に思っていたより時間がかかってしまい、当初のREADMEの予定より機能を縮小してMVPリリースをしようと考えているのですが、現段階でMVPリリースをして良いかどうかご意見をいただきたいです。

**次の機能は現段階で実装済みです。**
- 会員登録
- ログイン
- 映画登録
- レビュー登録
- レーティング
- ユーザーランキング表示
- お気に入り
- レビューへのいいね機能
- レビューへのコメント機能

**また、本リリースまでに下記を実装しようと考えています。**
- 管理画面
- オートコンプリート
- 検索機能
- レコメンド
- 画面のSPA化など

**README提出時との予定変更点は下記になります。**
- 検索機能　→MVPで予定していたがオートコンプリートとともに本リリースで実装
- レコメンド　→MVPで予定していたが本リリースで実装

**映画のサムネイルについて**
こちらも当初はユーザーの入力した単語に基づいてAI画像生成をする予定でしたが、stablediffusion、OpenAiのDALL-E3のAPIを使用していましたが精度があまり良くないため、下記のように変更しております。
Pexelsというフリー画像検索サイトのAPIを使用し、ユーザーに画像を検索してもらい、その画像をポスター画像として登録すると自動で映画のタイトルテキストがポスター画像の上に表示されるという機能にしました。
Pexels https://www.pexels.com/ja-jp/api/

必要最低限のものしか実装できておりませんが、このアプリの核となる機能は実装できていると考えております。
上記の機能でMVPリリースをして良いか、またテストはMVPリリース前にした方が良いのかの意見をお伺いしたいです。
また、他に最低限MVPまでにこれは必要というのがあればお教えいただきたいです。

**Comment by kenchasonakai** [comment]
MVPリリースレビューは以下の観点で行います
READMEの内容と変更したい時はWebアプリコミュニティで再度READMEレビュー依頼をお願いします

> MVPリリース時には、「READMEに記載されている内容が実装されているか」というポイントを確認しています！

**Comment by Tsuchiya2** [comment]
READMEレビュー（ https://github.com/koseki0830/imaginary_movie/pull/1 ）時に提出された内容をMVPレビューでは確認しますので、READMEレビューの内容が満たせている状態＆デプロイされていて動く＋エラーが出ない状態になったら提出(MVPレビュー)いただければ大丈夫です。
