### ISSUE TITLE
Power up vol.1

### ISSUE THREAD

**Issue by Tsuchiya2** [koseki0830/imaginary_movie#155]
MVPレビューお疲れ様でした。
これから就活に向けて、webアプリをパワーアップしていきましょう！

MVPリリースレビューの内容をまず再掲載いたしますね。
### より良いサービスのための提案
- ポスター画像生成：あらすじから画像を生成する機能があっても良いかと。また、生成した画像(キーワードで生成を含む)をそのまま選択して映画登録できるようにすると手間(専門ページへの遷移とか画像保存の手間etc)が省けて、ユーザーの体験が向上しそうです。（画像生成部分、モーダルで表示してその中から選択できると、あらすじの内容とか消えずに登録できたりと利点がありそうです）
- あらすじの部分：書けない人向けにAIがキーワードを複数選ぶと書いてくれる機能とかあると、そうしたユーザーも楽しめる＆書ける人もそれを読んで楽しめそうかとアプリを触っていて感じました。（こちらもモーダルにキーワード選択とかキーワード入力して実行ボタンを押すと、あらすじにそれが入っているとか）
- ハンバーガメニューが動くようにしましょう。
- レスポンシブ対応のちょっと見直し：マイページのサイドバー・ヘッダーの文字部分(プライバシーポリシーだけ改行されているetc）
- 虚構映画へレビューに対してコメントする意図をあまり感じられなかったのですが、ユーザーにどんな風に使ってもらいたいのかをもう少し詰めて考えてみましょう。
- HTMLの要素と要素の境界線が近すぎる箇所（コメントページの'登録する'ボタンetc）があるので確認をお願いします。

```
■来週の火曜日までに行っていただきたいこと（優先度高い順に記載）
1. 独自ドメイン導入
2. 利用規約・プライバシーポリシー
3. ハンバーガメニュー動くようにする   <---- この辺までは完了を期待しています
4. レスポンシブ対応のちょっと見直し
5. HTMLの要素と要素の境界線が近すぎる箇所の修正
```

上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。

12/12(火)を目処にレビューしますので、完了次第ご連絡ください。
よろしくお願いいたします。

**Comment by koseki0830** [comment]
お疲れ様でございます。
現状報告致します。
ご確認お願い致します。
 [アプリURL](https://imaginary-movie.fly.dev)

**独自ドメイン導入**
お名前.comでドメイン取得後、DNSレコード変更して反映を待っている状況です。
何日かかかる場合があるようなので、反映されない場合は再度確認してみます。

**利用規約・プライバシーポリシー**
実装しました。

**ハンバーガーメニュー**
ハンバーガーメニューは元々実装予定にはなく、コピーしたコンポーネンツにたまたま入っておりスマホでアプリの画面を確認していなかったため気づいておりませんでした。
スマホ時はハンバーガーメニューではなくヘッダーのナビゲーション各メニューが縦に並ぶようにして整えました。

**レスポンシブ対応のちょっと見直し**
- フッター
スマホ時プライバシーポリシーのみ改行されているところに関しては、フッターメニューを縦に並べて見た目整えました。

- マイページ
マイページはサイドバーではなく上部にメニューバーを表示して、メインコンテンツ(ブックマーク映画やレビュー済みの映画)は映画一覧と同じコードにして整えました。
スマホ時でも上部に各マイページメニューが表示されてパソコン画面同様操作できます。

- ユーザーランキング画面
スマホ時は横幅が足りず各ユーザーの最新3作品の一つが画面外に出てしまっていたのですが、映画を2列で表示して全部1つの画面に収まるようにしました。


**HTMLの要素と要素の境界線が近すぎる箇所の修正**
- コメント登録とフッターが近すぎる箇所修正
- 映画一覧画面のカテゴリー一覧と映画のコンテンツが近すぎる箇所修正


**MVPレビューに関して現状お答えできるところ**
虚構映画へレビューに対してコメントする意図について
このアプリは映画のあらすじだけでなく、レビューを投稿する点についても楽しさがあると思っており、そのレビューに対して他ユーザーからコメントが来ても嬉しいのかなと思って実装しました。
通常の映画レビューサイトでもレビューへのコメント機能がありますし、ユーザー同士の交流という意味でもあるかなと思います。

**Comment by Tsuchiya2** [comment]
上記及びサービス拝見しました。
ドメインの問題は少し様子を見る旨、承知しました。
いろいろなご対応ありがとうございます！

<br />

> 虚構映画へレビューに対してコメントする意図について
このアプリは映画のあらすじだけでなく、レビューを投稿する点についても楽しさがあると思っており、そのレビューに対して他ユーザーからコメントが来ても嬉しいのかなと思って実装しました。
通常の映画レビューサイトでもレビューへのコメント機能がありますし、ユーザー同士の交流という意味でもあるかなと思います。

こちら私の説明不足だったかもしれません。以下の画像のように映画へのコメントに対して、詳細ページが設けられており、そこに更にコメントができることの意図が分からなかったということになります。1つ前の映画に対してコメントは投稿できるので、こちらのコメント詳細ページから投稿できるコメントは何に使うのかが気になった次第です。
<img width="495" alt="スクリーンショット 2023-12-12 13 30 11" src="https://github.com/koseki0830/imaginary_movie/assets/61481161/476ff4b6-b914-4222-8e89-b31c654ce891">

<br /><br />

ヘッダーのところももう少し手を入れておきましょうか。ボタンのところだけ1つ下がったところではなく、同じ並びにした方が見栄えがスッキリするかと思いました。
<img width="953" alt="スクリーンショット 2023-12-12 13 33 03" src="https://github.com/koseki0830/imaginary_movie/assets/61481161/d7694d22-60f5-40fd-8121-3264c11817c3">
<img width="480" alt="スクリーンショット 2023-12-12 13 33 13" src="https://github.com/koseki0830/imaginary_movie/assets/61481161/750f9773-8f68-43c2-9e12-44c535310f27">

**Comment by Tsuchiya2** [comment]
MVP機能に書かれている「レコメンド」と「ページの見た目の整え(全体)」「ドメイン対応」の3つを優先に取り組んでいただき、その後以下をサービスに加えるかの検討etcと、コードのリファクタを行いましょう！

■検討①
> ポスター画像生成：あらすじから画像を生成する機能があっても良いかと。また、生成した画像(キーワードで生成を含む)をそのまま選択して映画登録できるようにすると手間(専門ページへの遷移とか画像保存の手間etc)が省けて、ユーザーの体験が向上しそうです。（画像生成部分、モーダルで表示してその中から選択できると、あらすじの内容とか消えずに登録できたりと利点がありそうです）

■検討②
> あらすじの部分：書けない人向けにAIがキーワードを複数選ぶと書いてくれる機能とかあると、そうしたユーザーも楽しめる＆書ける人もそれを読んで楽しめそうかとアプリを触っていて感じました。（こちらもモーダルにキーワード選択とかキーワード入力して実行ボタンを押すと、あらすじにそれが入っているとか）

■コードのリファクタ箇所
・app/models/user.rbのtop_categories_moviesメソッド内の`Movie.joins...`のところ
=> Movieモデルにscopeもしくはクラスメソッドを定義して、それを呼び出す形に修正

・app/controllers/movies_controller.rbの独自アクションのところ
=> だいぶ独自アクションがあるので、リソースベースのルーティングに修正していきましょう。例えばbookmarksアクションは、bookmarks_ccontroller#indexに切り出すなど、個々のリソースを見出してルーティングを設定していく方がRailsっぽくなりますので、`Rails リソースベース ルーティング`などで調べたりして、独自アクションを切り出していきましょう。

**Comment by Tsuchiya2** [comment]
https://github.com/koseki0830/imaginary_movie/issues/155#issuecomment-1851287652
https://github.com/koseki0830/imaginary_movie/issues/155#issuecomment-1851298118

上記コメントに記載しましたことを来週の火曜日まで取り組み、また状況の共有をお願いできますでしょうか。

よろしくお願いいたします。

**Comment by koseki0830** [comment]
お疲れ様です。
前回からの変更点報告します。

### 実装済み
**レコメンド**
MVPリリースで実装済みです。
マイページのあなたへのおすすめにおすすめの映画を表示しています。

**ページの見た目整え**
ヘッダーのナビゲーション要素とログイン・ログアウトボタンの位置を揃えました。

**ドメイン対応**
独自ドメイン化しました。
[アプリURL](https://kyoko-eiga.com)

**ポスター画像生成**
モーダルの中で検索と検索結果の表示ができるようにしました。
ただその中で画像を選択して直接フォームに送信するのはこれから実装します。

### 検討
**あらすじ入力補助機能**
書けない人向けにAIがキーワードを複数選ぶと書いてくれる機能・また映画のカテゴリーごとにこちらからフォーマットを提供して、あらすじの中の人名や固有名詞のみをユーザーに入力してもらうのも良いと思っており迷っています。
本リリースに追加できるかどうかは未定でありリリース後になる可能性もあります。

**あらすじから画像生成について**
MVP前の段階でOpenAIのDALL E3やstablediffusionのAPIを使ってユーザーが入力した短いプロンプトから画像生成する機能を以前は実装していましたが、精度が低く使い物にならなかったため現在のようなフリー画像の方にしています。
文章が長ければさらに精度が低くなり意味がないと思ったためこちらは断念しています。

**コメント機能について**
映画に対して付くのが「レビュー」
レビューに対して付くのが「コメント」
というイメージです。
下記はレビューの詳細画面で、レビュー内容が表示されています。
[![Image from Gyazo](https://i.gyazo.com/3f8eaf5198d254a37897aae3e3c565c3.png)](https://gyazo.com/3f8eaf5198d254a37897aae3e3c565c3)

下記はレビュー詳細下部のコメントゾーンで、レビューに対して付いたコメント　ということになります。
[![Image from Gyazo](https://i.gyazo.com/7cc262956c50faa32cf0eb0245c4559e.png)](https://gyazo.com/7cc262956c50faa32cf0eb0245c4559e)

**Comment by koseki0830** [comment]
管理画面についても実装済みです。
レビューサービスという面もあるが基本的にはCGMであり、ユーザーがコンテンツを投稿して成り立つサービスであるため、管理画面では不適切な投稿やユーザーの削除を最低限できるようにしております。
rails_adminとcancancanというgemで実装しました。

usersテーブルのadminカラムがtrueのユーザーにのみフッターに下記のリンクが表示されます。
[![Image from Gyazo](https://i.gyazo.com/60f6950563d6cc55be8e74af5335cd89.png)](https://gyazo.com/60f6950563d6cc55be8e74af5335cd89)

管理画面のページです。
[![Image from Gyazo](https://i.gyazo.com/0aaf6bb5bdfcc5af1fe27c0ae89bc32d.png)](https://gyazo.com/0aaf6bb5bdfcc5af1fe27c0ae89bc32d)

一応本リリースまでの予定機能全て実装済みなので、あとはコードのリファクタリングのみとなります。

**Comment by Tsuchiya2** [comment]
共有ありがとうございます！

■完了
- レコメンド
- ページの見た目整え
- ドメイン対応
- ポスター画像生成
- 管理画面

順調ですね！そのまま進めましょう！

<br />

■検討
個々の項目に対して、コメントしました🙏

- あらすじ入力補助機能：コメントに書いていただいた件、承知しました。優先度は最優先でなくても良いかと思いますので、引き続き検討含めてお願いします。
- あらすじから画像生成について：承知しました。理由も添えられていて良いと思います。
- コメント機能について：承知しました。イメージが深まりました。レビューに対するコメントが少ないと、機能として何を行うものなのかが初見の人には？？となってしまうので、何か対策を行っておくと、コメント数の増加に繋がるかと思います。例えば、コメントに対してAIが何某かのテキストを投稿してくれるとか、初期はご自身で各コメントに回答するとか行うなどをしておくと良いかと。（優先度は高くなくて大丈夫です）
<br />

■追加で優先して取り組んでいただきたいこと
サービスを改めて触っていて気になった点をお伝えします。
以下の画像のように縦長のものと、そうでないものが混在している場合、統一感が崩れてしまっているのが気になりました。他のものより見た目のインパクトが強い部分なので、こちらを優先に対応をお願いしたいです。
<img width="880" alt="スクリーンショット 2023-12-19 20 44 21" src="https://github.com/koseki0830/imaginary_movie/assets/61481161/bbb35571-b91e-48e0-b673-2291bd0557f2">

修正の方向性としては、小さい画面で虚構映画が縦1列に並んでいる場合は現状のままで大丈夫です。横に2つ以上並んで表示される際に、縦長に画像を揃えるのか、そうでないものに揃えるか統一するのを検討してください。

理由としては、タイトル等を目で追う際にユーザーの視線が上下に動いてしまうのは、見た人に統一性が無いものとして映ってしまうため、マイナス面を減らすことが目的になります。

<br />

■細かい点ですが気になったこと
・ページネーションにカーソルを合わせた際に、文字列のところが数値のところと異なる表示にある点が気になりました。
<img width="332" alt="スクリーンショット 2023-12-19 20 59 18" src="https://github.com/koseki0830/imaginary_movie/assets/61481161/4bd95486-f353-4fdb-aaa4-55ec6727ed10">

・投稿者の名前に色がついておりますが、ユーザーの詳細が閲覧できるリンクのように映ってしまうため、他の文字列と同じ色に統一してしまっても良いかと思いました。（リンクだと思ってクリックしたら違ったという体験を発生させないため。ユーザー体験の観点から）
<img width="324" alt="スクリーンショット 2023-12-19 21 00 25" src="https://github.com/koseki0830/imaginary_movie/assets/61481161/cb1937f4-0d7e-4a93-a43f-add11ebc8954">

・ユーザープロフィール編集ですが、「ブックマークした映画」「レビューした映画」「あなたへのおすすめ」が並ぶ中で、これだけ浮いてしまっているように感じました。思いつきのアイディアですが、ログアウトボタンのところをユーザーのアイコンか何を表示して、それをクリックすると、「プロフィール編集」「ログアウト」が表示され、それぞれクリックできるようにする感じとかどうでしょうか。プロフィール編集はクリックするとモーダル表示でユーザーネーム等を変更できるフォームが表示される感じとかのイメージです。
<img width="842" alt="スクリーンショット 2023-12-19 21 03 36" src="https://github.com/koseki0830/imaginary_movie/assets/61481161/5f56dadb-4084-4691-a199-e7f30aec9519">

**Comment by koseki0830** [comment]
お疲れ様です。
面接対策をしておりアプリの方は現状あまり進められておりませんが、進捗報告します。

### 前回からの変更点

**映画一覧の画像の大きさ**
全ての画像で画像の大きさとグリッドの大きさを統一しました。

**ページネーションのスタイリング**
ご指摘のとおり数字と文字列でスタイルが違うのは違和感があったのと、そもそもページネーションで文字列はわかりにくいと思ったので、文字列をやめてfont-awesomeで記号にして直感的にしました。
[![Image from Gyazo](https://i.gyazo.com/141f863d8886812d3921f7ff534e1900.png)](https://gyazo.com/141f863d8886812d3921f7ff534e1900)

**投稿者の名前の色**
他の色と統一しました。
そのユーザーの投稿した映画一覧画面　を今後実装することがあれば色をつけてリンクにしようと思います。

1/8から順次応募に入れればと思っているので、その他については面接練習や企業選定と並行して進め、1/8より前には本リリース予定です。

**Comment by Tsuchiya2** [comment]
ありがとうございます！

- 映画一覧の画像の大きさ
- ページネーションのスタイリング
- 投稿者の名前の色

面接対策の中、上記完了されたということで良いですね！

サービスの方も触りましたが、残っている部分以外は初期よりだいぶ良くなったかと思います！

あとは細かい部分と検証に残っているものだけかと思いますので、本リリース・就活と並行して進めてもらえれば大丈夫かと感じました！

**LGTMです！**

引き続き開発＆就活の準備頑張ってください！

**Comment by Tsuchiya2** [comment]
=== 追記 ===

開発の進捗共有も本日をもって終了で大丈夫です！
何かあればスレッドの方にご連絡ください！

**Comment by koseki0830** [comment]
ご確認ありがとうございます！
承知しました。
