### ISSUE TITLE
バリデーションエラーメッセージが表示できない

### ISSUE THREAD

**Issue by koseki0830** [koseki0830/imaginary_movie#96]
- 質問内容・実現したいこと
各フォームで個別のバリデーションエラーメッセージの表示がしたいです。
記載したコードのどこに問題があるのか現状わからない状態なので確認お願いします。
下記ではUser登録の際を例で挙げておりますが、他のフォームでも同様にエラーメッセージが表示されません。

- 現状発生している問題・エラーメッセージ
バリデーションを設定しており、viewで表示するコードを記載しているが、メッセージが表示されない。

- どの処理までうまく動いているのか
error自体が取得できていないと思い、エラーが発生するようなユーザーを作ったら下記のようにerrorが取得できた。
```
[1] pry(main)> user = User.create
  TRANSACTION (0.1ms)  BEGIN
  User Exists? (0.6ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" IS NULL LIMIT $1  [["LIMIT", 1]]
  TRANSACTION (0.1ms)  ROLLBACK
=> #<User:0x00000001069a7890
 id: nil,
 name: nil,
 email: nil,
 crypted_password: nil,
 salt: nil,
 created_at: nil,
 updated_at: nil,
 reset_password_token: nil,
 reset_password_token_expires_at: nil,
 reset_password_email_sent_at: nil,
 access_count_to_reset_password_page: 0>
[2] pry(main)> user.errors.full_messages
=> ["ユーザーネームを入力してください", "メールアドレスを入力してください", "パスワードは3文字以上で入力してください", "パスワード確認を入力してください"]
[3] pry(main)> 



```

また、バリデーションも効いている。
```
[3] pry(main)> user.valid?
  User Exists? (0.8ms)  SELECT 1 AS one FROM "users" WHERE "users"."email" IS NULL LIMIT $1  [["LIMIT", 1]]
=> false

```

- 該当のソースコード
views/users/new.html(抜粋)
```
    <%= form_with model: @user, local: true do |f| %>
      <% if @user.errors.any? %>
        <div class="bg-red-100 border border-red-500 text-red-700 px-4 py-3 rounded">
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

```

users_controllerのcreateアクション
```
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = t('.success')
      redirect_to login_path 
    else
      render :new
    end
  end
```

- 試したこと
cssに問題があるのではと思い、users/newで下記のようにして確認した。
```
<div class="bg-red-100 border border-red-500 text-red-700 px-4 py-3 rounded">
   <p>こんにちは</p>
 </div>

```
その結果、しっかり表示された。
[![Image from Gyazo](https://i.gyazo.com/6d5a449e466466a4f1036885701073cc.png)](https://gyazo.com/6d5a449e466466a4f1036885701073cc)

- エラーから考えられる原因
cssやerrorsの取得、バリデーションには問題がないことがわかったため、controllerの記載やhtmlコードの記載方法が間違っている可能性がある。

- 参考にしたサイト
　https://school.runteq.jp/v2/curriculums/rails_basic/chapters/11

　https://qiita.com/mmaumtjgj/items/c055fe920dcfcb824981

**Comment by kenchasonakai** [comment]
一度`Rails7 バリデーションエラー 表示されない`などで調べてみてください

**Comment by koseki0830** [comment]
https://qiita.com/P-man_Brown/items/862503a638801fea01e7
上記を参考にしたら実装できました。
初歩的なことですが、Railsのバージョンによって対応が変わる可能性を見逃しておりました。
ありがとうございます!
